# Generated by Django 2.2.1 on 2019-05-15 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meanspaymentsale',
            name='value',
            field=models.DecimalField(db_column='nb_value', decimal_places=4, max_digits=16),
        ),
    ]
