# Generated by Django 2.2.1 on 2019-05-21 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190515_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='subtotal',
            field=models.DecimalField(db_column='nb_subtotal', decimal_places=4, max_digits=10, null=True),
        ),
    ]
