# Generated by Django 2.2.1 on 2019-05-21 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_saleitem_subtotal'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovementStock',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at', null=True)),
                ('date', models.DateField(db_column='dt_movement_stock')),
                ('type', models.CharField(choices=[('I', 'In'), ('O', 'Out')], db_column='cs_type', max_length=1)),
                ('document', models.CharField(db_column='tx_document', max_length=64, null=True)),
            ],
            options={
                'db_table': 'movement_stock',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StockAddress',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at', null=True)),
                ('description', models.CharField(db_column='tx_description', max_length=104)),
            ],
            options={
                'db_table': 'stock_address',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MovementStockItem',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at', null=True)),
                ('quantity', models.DecimalField(db_column='nb_quantity', decimal_places=3, max_digits=10)),
                ('movement_stock', models.ForeignKey(db_column='id_movement_stock', db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, to='core.MovementStock')),
                ('product', models.ForeignKey(db_column='id_product', db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Product')),
            ],
            options={
                'db_table': 'movement_stock_item',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='movementstock',
            name='stock_address',
            field=models.ForeignKey(db_column='id_stock_address', db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, to='core.StockAddress'),
        ),
        migrations.AddIndex(
            model_name='movementstockitem',
            index=models.Index(fields=['movement_stock'], name='movement_st_id_move_212a97_idx'),
        ),
        migrations.AddIndex(
            model_name='movementstockitem',
            index=models.Index(fields=['product'], name='movement_st_id_prod_fb4642_idx'),
        ),
        migrations.AddIndex(
            model_name='movementstock',
            index=models.Index(fields=['stock_address'], name='movement_st_id_stoc_a291e8_idx'),
        ),
    ]
