version: '3'
services:

  redis:
    image: redis:alpine
    hostname: redis
    ports:
      - 6379:6379

  postgres:
    restart: always
    image: postgres:9.5.3
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_DB=sale
    - POSTGRES_PASSWORD=123456
    ports:
    - "5432:5432"

networks:
  default:
    external:
      name: sale_network
